# How to execute:
# $ docker build -t fiwaredashboard .
# $ docker run -p 3000:3000 -d fiwaredashboard

FROM fiware/fiwarecentos
WORKDIR /opt
RUN yum -y install git
RUN curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
RUN yum -y groupinstall 'Development Tools'
RUN yum -y install nodejs
RUN yum -y install rpm-build
RUN yum -y install initscripts
RUN yum -y install crontabs
RUN git clone https://github.com/telefonicaid/fiware-health /opt/fiware-health
ARG BRANCH=develop
RUN cd /opt/fiware-health; git checkout ${BRANCH}
WORKDIR /opt/fiware-health/dashboard
RUN npm install -g grunt-cli
RUN npm install
RUN grunt test
RUN sed -i 's/production/development/' Gruntfile.js
COPY sonar-project.properties sonar-project.properties
CMD grunt test; grunt lint-report test-report coverage-report
